"""
    Program Management Service

    A set of API endpoints that allow you to get, update, delete an education group.  # noqa: E501

    The version of the OpenAPI document: 1.4
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_program_management_sdk
from osis_program_management_sdk.model.node_base import NodeBase
globals()['NodeBase'] = NodeBase
from osis_program_management_sdk.model.program_tree_prerequisites import ProgramTreePrerequisites


class TestProgramTreePrerequisites(unittest.TestCase):
    """ProgramTreePrerequisites unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProgramTreePrerequisites(self):
        """Test ProgramTreePrerequisites"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProgramTreePrerequisites()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
