"""
    Program Management Service

    A set of API endpoints that allow you to get, update, delete an education group.  # noqa: E501

    The version of the OpenAPI document: 1.4
    Generated by: https://openapi-generator.tech
"""


import unittest

import osis_program_management_sdk
from osis_program_management_sdk.api.programme_api import ProgrammeApi  # noqa: E501


class TestProgrammeApi(unittest.TestCase):
    """ProgrammeApi unit test stubs"""

    def setUp(self):
        self.api = ProgrammeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_programmes_list(self):
        """Test case for programmes_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
