"""
    Program Management Service

    A set of API endpoints that allow you to get, update, delete an education group.  # noqa: E501

    The version of the OpenAPI document: 1.4
    Generated by: https://openapi-generator.tech
"""


import unittest

import osis_program_management_sdk
from osis_program_management_sdk.api.trainings_api import TrainingsApi  # noqa: E501


class TestTrainingsApi(unittest.TestCase):
    """TrainingsApi unit test stubs"""

    def setUp(self):
        self.api = TrainingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_training_prerequisites_official(self):
        """Test case for training_prerequisites_official

        """
        pass

    def test_training_prerequisites_transition(self):
        """Test case for training_prerequisites_transition

        """
        pass

    def test_training_prerequisites_version(self):
        """Test case for training_prerequisites_version

        """
        pass

    def test_training_prerequisites_version_transition(self):
        """Test case for training_prerequisites_version_transition

        """
        pass


if __name__ == '__main__':
    unittest.main()
