# flake8: noqa

"""
    Program Management Service

    A set of API endpoints that allow you to get, update, delete an education group.  # noqa: E501

    The version of the OpenAPI document: 1.4
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.4"

# import ApiClient
from osis_program_management_sdk.api_client import ApiClient

# import Configuration
from osis_program_management_sdk.configuration import Configuration

# import exceptions
from osis_program_management_sdk.exceptions import OpenApiException
from osis_program_management_sdk.exceptions import ApiAttributeError
from osis_program_management_sdk.exceptions import ApiTypeError
from osis_program_management_sdk.exceptions import ApiValueError
from osis_program_management_sdk.exceptions import ApiKeyError
from osis_program_management_sdk.exceptions import ApiException
